# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added

- Initial project setup with TypeScript and React
- GitHub contribution graph component with customizable themes
- 9 built-in themes (GitHub, Shadcn, Vesper, Vercel, 11Labs, Prisma, Supabase, Ayu, Atom)
- Dark and Light mode support
- Responsive design for all screen sizes
- React Query integration for data caching
- SSR support for Next.js
- Accessibility features with ARIA labels
- Comprehensive TypeScript definitions
- Monorepo setup with docs and example apps
- CI/CD pipeline with automated testing, deployment, and publishing

### Features

- **OctoGraph Component**: Main component for rendering GitHub activity graphs
- **Theme System**: Extensible theming with built-in and custom theme support
- **Data Fetching**: Optimized GitHub API integration with caching
- **Accessibility**: Full keyboard navigation and screen reader support
- **Performance**: Tree-shakeable bundle with lazy loading
- **Developer Experience**: Comprehensive documentation and examples

---

_This changelog is automatically generated by [Changesets](https://github.com/changesets/changesets) based on semantic version updates. Each release will add entries to this file with detailed information about new features, bug fixes, and breaking changes._

## How to Read This Changelog

- **Added** for new features
- **Changed** for changes in existing functionality
- **Deprecated** for soon-to-be removed features
- **Removed** for now removed features
- **Fixed** for any bug fixes
- **Security** for vulnerability fixes

## Version Guidelines

This project follows [Semantic Versioning](https://semver.org/):

- **MAJOR** version for incompatible API changes
- **MINOR** version for backwards-compatible functionality additions
- **PATCH** version for backwards-compatible bug fixes
